# Automatically generated by Breeze on 2017-09-29T18:18:52.501447
# Any change WILL BE OVERWRITTEN by Breeze
from utilz import magic_const, MagicAutoConstEnum


# Static object describing available Environments
# noinspection PyMethodParameters,PyPep8Naming
class ConfigEnvironmentsList(MagicAutoConstEnum):
	@magic_const
	def FIMMCloud(): pass

	@magic_const
	def FIMM(): pass


config_list = ConfigEnvironmentsList()
